-- Add missing columns to items table
ALTER TABLE items ADD COLUMN
IF NOT EXISTS negotiable BOOLEAN DEFAULT FALSE;
ALTER TABLE items ADD COLUMN
IF NOT EXISTS firm BOOLEAN DEFAULT FALSE;
ALTER TABLE items ADD COLUMN
IF NOT EXISTS payment_methods JSONB DEFAULT '[]'::JSONB;
ALTER TABLE items ADD COLUMN
IF NOT EXISTS trade_description TEXT;
ALTER TABLE items ADD COLUMN
IF NOT EXISTS trade_preference TEXT;
ALTER TABLE items ADD COLUMN
IF NOT EXISTS meetup_locations JSONB DEFAULT '[]'::JSONB;
ALTER TABLE items ADD COLUMN
IF NOT EXISTS availability JSONB DEFAULT '[]'::JSONB;
ALTER TABLE items ADD COLUMN
IF NOT EXISTS special_instructions TEXT;
